# Generated by Django 4.2.10 on 2024-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("requests", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("guests", models.IntegerField()),
            ],
        ),
    ]
