# Generated by Django 4.2.10 on 2024-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0002_book"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="id",),
        migrations.AlterField(
            model_name="book", name="guests", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="phone",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
